[package]
name = "codegen"
version = "0.1.0"
authors = ["Yukio Usuzumi <anohigisavay@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
linked-hash-map = { version = "0.5.1", features = ["serde_impl"] }
